#!/bin/bash

# Attempt to set APP_HOME
# Resolve links: $0 may be a link
PRG="$0"
# Need this for relative symlinks.
while [ -h "$PRG" ] ; do
    ls=`ls -ld "$PRG"`
    link=`expr "$ls" : '.*-> \(.*\)$'`
    if expr "$link" : '/.*' > /dev/null; then
        PRG="$link"
    else
        PRG=`dirname "$PRG"`"/$link"
    fi
done
SAVED="`pwd`"
cd "`dirname \"$PRG\"`/.." >&-
APP_HOME="`pwd -P`"
cd "$SAVED" >&-

CLASSPATH=
for file in $APP_HOME/lib/*.jar
do
    CLASSPATH=$file:$CLASSPATH
done

DEFAULT_SERVER_MEMORY="--initial-heap=2g --max-heap=2g"

DEFAULT_JVM_OPTS=" --J=-XX:+UseParNewGC"
DEFAULT_JVM_OPTS="$DEFAULT_JVM_OPTS --J=-XX:+UseConcMarkSweepGC"
DEFAULT_JVM_OPTS="$DEFAULT_JVM_OPTS --J=-XX:CMSInitiatingOccupancyFraction=50"
DEFAULT_JVM_OPTS="$DEFAULT_JVM_OPTS --J=-XX:+CMSParallelRemarkEnabled"
DEFAULT_JVM_OPTS="$DEFAULT_JVM_OPTS --J=-XX:+UseCMSInitiatingOccupancyOnly"
DEFAULT_JVM_OPTS="$DEFAULT_JVM_OPTS --J=-XX:+ScavengeBeforeFullGC"
DEFAULT_JVM_OPTS="$DEFAULT_JVM_OPTS --J=-XX:+CMSScavengeBeforeRemark"
DEFAULT_JVM_OPTS="$DEFAULT_JVM_OPTS --J=-XX:+UseCompressedOops"
DEFAULT_JVM_OPTS="$DEFAULT_JVM_OPTS --mcast-port=0"

GEODE_OPTIONS="--name=server1 "
GEODE_OPTIONS="${GEODE_OPTIONS} --locators=localhost[10334]"
GEODE_OPTIONS="${GEODE_OPTIONS} --dir=${APP_HOME}/data/server1"
GEODE_OPTIONS="${GEODE_OPTIONS} --server-port=0"
GEODE_OPTIONS="${GEODE_OPTIONS} --J=-Dgemfire.start-locator=localhost[10334]"
GEODE_OPTIONS="${GEODE_OPTIONS} --J=-Dgemfire.jmx-manager=true"
GEODE_OPTIONS="${GEODE_OPTIONS} --J=-Dgemfire.jmx-manager-start=true"
GEODE_OPTIONS="${GEODE_OPTIONS} --classpath=${CLASSPATH}"
GEODE_OPTIONS="${GEODE_OPTIONS} --eviction-heap-percentage=75"
GEODE_OPTIONS="${GEODE_OPTIONS} --critical-heap-percentage=90"
GEODE_OPTIONS="${GEODE_OPTIONS} --bind-address=localhost"

mkdir -p ${APP_HOME}/data/server1


gfsh << EOF
   start server ${DEFAULT_SERVER_MEMORY} ${DEFAULT_JVM_OPTS} ${GEODE_OPTIONS}
EOF
